COLUMN NAME                     FORMAT A25         HEADING "NAME"
COLUMN SCN                      FORMAT 99999999999999999    HEADING "SCN"
COLUMN TIME                     FORMAT A26         HEADING "TIME"
COLUMN DATABASE_INCARNATION#    FORMAT 99999       HEADING "INCARN#"
COLUMN GUARANTEE_FLASHBACK_DATABASE FORMAT A5      HEADING "GFB"
COLUMN STORAGE_SIZE             FORMAT 99999999999999       HEADING "STORAGE_SIZE(B)"
SET LINESIZE 300

SELECT
  NAME,
  SCN,
  TIME,
  DATABASE_INCARNATION#,
  GUARANTEE_FLASHBACK_DATABASE,
  STORAGE_SIZE
FROM
  V$RESTORE_POINT;
