ALTER TABLESPACE Your_Tablespace_Name ADD DATAFILE '/path/to/your/datafile.dbf' SIZE 100M;

ALTER TABLESPACE OBIA_QMI_DATA ADD DATAFILE '+DATAC1' SIZE 30G;

ALTER TABLESPACE OBIA_DW_DATA ADD DATAFILE SIZE 10G AUTOEXTEND ON NEXT 100M MAXSIZE 30G;
