SELECT 
    FILE_NAME, 
    FILE_ID, 
    TABLESPACE_NAME, 
    ROUND(BYTES/1024/1024/1024,2) AS SIZE_GB, 
    BLOCKS, 
    STATUS, 
    AUTOEXTENSIBLE, 
    ONLINE_STATUS, 
    LOST_WRITE_PROTECT,
    TO_NUMBER(REGEXP_SUBSTR(FILE_NAME, 'xxapps_ts_tx_data_([0-9]+)', 1, 1, NULL, 1)) AS FILE_NUMBER
FROM 
    dba_data_files 
WHERE 
    TABLESPACE_NAME IN ('XXAPPS_TS_TX_DATA') 
    AND FILE_NAME LIKE '%+DG_CRTPRD_DT01%' 
ORDER BY 
    FILE_NUMBER ASC;
